/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VereadoresRouteImport } from './routes/vereadores'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as SicRouteImport } from './routes/sic'
import { Route as PublicacoesRouteImport } from './routes/publicacoes'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as OuvidoriaRouteImport } from './routes/ouvidoria'
import { Route as MapaDoSiteRouteImport } from './routes/mapa-do-site'
import { Route as LicitacoesRouteImport } from './routes/licitacoes'
import { Route as LeisRouteImport } from './routes/leis'
import { Route as InstitucionalRouteImport } from './routes/institucional'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminVereadoresRouteImport } from './routes/_authenticated/admin.vereadores'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminPublicacoesRouteImport } from './routes/_authenticated/admin.publicacoes'
import { Route as AuthenticatedAdminProjetosRouteImport } from './routes/_authenticated/admin.projetos'
import { Route as AuthenticatedAdminPaginasRouteImport } from './routes/_authenticated/admin.paginas'
import { Route as AuthenticatedAdminNoticiasRouteImport } from './routes/_authenticated/admin.noticias'
import { Route as AuthenticatedAdminLicitacoesRouteImport } from './routes/_authenticated/admin.licitacoes'
import { Route as AuthenticatedAdminLeisRouteImport } from './routes/_authenticated/admin.leis'
import { Route as AuthenticatedAdminDocumentosRouteImport } from './routes/_authenticated/admin.documentos'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin.banners'

const VereadoresRoute = VereadoresRouteImport.update({
  id: '/vereadores',
  path: '/vereadores',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const SicRoute = SicRouteImport.update({
  id: '/sic',
  path: '/sic',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacoesRoute = PublicacoesRouteImport.update({
  id: '/publicacoes',
  path: '/publicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const OuvidoriaRoute = OuvidoriaRouteImport.update({
  id: '/ouvidoria',
  path: '/ouvidoria',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaDoSiteRoute = MapaDoSiteRouteImport.update({
  id: '/mapa-do-site',
  path: '/mapa-do-site',
  getParentRoute: () => rootRouteImport,
} as any)
const LicitacoesRoute = LicitacoesRouteImport.update({
  id: '/licitacoes',
  path: '/licitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LeisRoute = LeisRouteImport.update({
  id: '/leis',
  path: '/leis',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalRoute = InstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminVereadoresRoute =
  AuthenticatedAdminVereadoresRouteImport.update({
    id: '/admin/vereadores',
    path: '/admin/vereadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPublicacoesRoute =
  AuthenticatedAdminPublicacoesRouteImport.update({
    id: '/admin/publicacoes',
    path: '/admin/publicacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProjetosRoute =
  AuthenticatedAdminProjetosRouteImport.update({
    id: '/admin/projetos',
    path: '/admin/projetos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaginasRoute =
  AuthenticatedAdminPaginasRouteImport.update({
    id: '/admin/paginas',
    path: '/admin/paginas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNoticiasRoute =
  AuthenticatedAdminNoticiasRouteImport.update({
    id: '/admin/noticias',
    path: '/admin/noticias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLicitacoesRoute =
  AuthenticatedAdminLicitacoesRouteImport.update({
    id: '/admin/licitacoes',
    path: '/admin/licitacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLeisRoute = AuthenticatedAdminLeisRouteImport.update({
  id: '/admin/leis',
  path: '/admin/leis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDocumentosRoute =
  AuthenticatedAdminDocumentosRouteImport.update({
    id: '/admin/documentos',
    path: '/admin/documentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/admin/configuracoes',
    path: '/admin/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/admin/banners',
    path: '/admin/banners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/institucional': typeof InstitucionalRoute
  '/leis': typeof LeisRoute
  '/licitacoes': typeof LicitacoesRoute
  '/mapa-do-site': typeof MapaDoSiteRoute
  '/ouvidoria': typeof OuvidoriaRoute
  '/projetos': typeof ProjetosRoute
  '/publicacoes': typeof PublicacoesRoute
  '/sic': typeof SicRoute
  '/transparencia': typeof TransparenciaRoute
  '/vereadores': typeof VereadoresRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
  '/admin/leis': typeof AuthenticatedAdminLeisRoute
  '/admin/licitacoes': typeof AuthenticatedAdminLicitacoesRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/admin/paginas': typeof AuthenticatedAdminPaginasRoute
  '/admin/projetos': typeof AuthenticatedAdminProjetosRoute
  '/admin/publicacoes': typeof AuthenticatedAdminPublicacoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vereadores': typeof AuthenticatedAdminVereadoresRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/institucional': typeof InstitucionalRoute
  '/leis': typeof LeisRoute
  '/licitacoes': typeof LicitacoesRoute
  '/mapa-do-site': typeof MapaDoSiteRoute
  '/ouvidoria': typeof OuvidoriaRoute
  '/projetos': typeof ProjetosRoute
  '/publicacoes': typeof PublicacoesRoute
  '/sic': typeof SicRoute
  '/transparencia': typeof TransparenciaRoute
  '/vereadores': typeof VereadoresRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/noticias': typeof NoticiasIndexRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
  '/admin/leis': typeof AuthenticatedAdminLeisRoute
  '/admin/licitacoes': typeof AuthenticatedAdminLicitacoesRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/admin/paginas': typeof AuthenticatedAdminPaginasRoute
  '/admin/projetos': typeof AuthenticatedAdminProjetosRoute
  '/admin/publicacoes': typeof AuthenticatedAdminPublicacoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vereadores': typeof AuthenticatedAdminVereadoresRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/institucional': typeof InstitucionalRoute
  '/leis': typeof LeisRoute
  '/licitacoes': typeof LicitacoesRoute
  '/mapa-do-site': typeof MapaDoSiteRoute
  '/ouvidoria': typeof OuvidoriaRoute
  '/projetos': typeof ProjetosRoute
  '/publicacoes': typeof PublicacoesRoute
  '/sic': typeof SicRoute
  '/transparencia': typeof TransparenciaRoute
  '/vereadores': typeof VereadoresRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
  '/_authenticated/admin/leis': typeof AuthenticatedAdminLeisRoute
  '/_authenticated/admin/licitacoes': typeof AuthenticatedAdminLicitacoesRoute
  '/_authenticated/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/_authenticated/admin/paginas': typeof AuthenticatedAdminPaginasRoute
  '/_authenticated/admin/projetos': typeof AuthenticatedAdminProjetosRoute
  '/_authenticated/admin/publicacoes': typeof AuthenticatedAdminPublicacoesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/vereadores': typeof AuthenticatedAdminVereadoresRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/institucional'
    | '/leis'
    | '/licitacoes'
    | '/mapa-do-site'
    | '/ouvidoria'
    | '/projetos'
    | '/publicacoes'
    | '/sic'
    | '/transparencia'
    | '/vereadores'
    | '/noticias/$slug'
    | '/noticias/'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/documentos'
    | '/admin/leis'
    | '/admin/licitacoes'
    | '/admin/noticias'
    | '/admin/paginas'
    | '/admin/projetos'
    | '/admin/publicacoes'
    | '/admin/usuarios'
    | '/admin/vereadores'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/institucional'
    | '/leis'
    | '/licitacoes'
    | '/mapa-do-site'
    | '/ouvidoria'
    | '/projetos'
    | '/publicacoes'
    | '/sic'
    | '/transparencia'
    | '/vereadores'
    | '/noticias/$slug'
    | '/noticias'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/documentos'
    | '/admin/leis'
    | '/admin/licitacoes'
    | '/admin/noticias'
    | '/admin/paginas'
    | '/admin/projetos'
    | '/admin/publicacoes'
    | '/admin/usuarios'
    | '/admin/vereadores'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/institucional'
    | '/leis'
    | '/licitacoes'
    | '/mapa-do-site'
    | '/ouvidoria'
    | '/projetos'
    | '/publicacoes'
    | '/sic'
    | '/transparencia'
    | '/vereadores'
    | '/noticias/$slug'
    | '/noticias/'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/documentos'
    | '/_authenticated/admin/leis'
    | '/_authenticated/admin/licitacoes'
    | '/_authenticated/admin/noticias'
    | '/_authenticated/admin/paginas'
    | '/_authenticated/admin/projetos'
    | '/_authenticated/admin/publicacoes'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/vereadores'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  InstitucionalRoute: typeof InstitucionalRoute
  LeisRoute: typeof LeisRoute
  LicitacoesRoute: typeof LicitacoesRoute
  MapaDoSiteRoute: typeof MapaDoSiteRoute
  OuvidoriaRoute: typeof OuvidoriaRoute
  ProjetosRoute: typeof ProjetosRoute
  PublicacoesRoute: typeof PublicacoesRoute
  SicRoute: typeof SicRoute
  TransparenciaRoute: typeof TransparenciaRoute
  VereadoresRoute: typeof VereadoresRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vereadores': {
      id: '/vereadores'
      path: '/vereadores'
      fullPath: '/vereadores'
      preLoaderRoute: typeof VereadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sic': {
      id: '/sic'
      path: '/sic'
      fullPath: '/sic'
      preLoaderRoute: typeof SicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicacoes': {
      id: '/publicacoes'
      path: '/publicacoes'
      fullPath: '/publicacoes'
      preLoaderRoute: typeof PublicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ouvidoria': {
      id: '/ouvidoria'
      path: '/ouvidoria'
      fullPath: '/ouvidoria'
      preLoaderRoute: typeof OuvidoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-do-site': {
      id: '/mapa-do-site'
      path: '/mapa-do-site'
      fullPath: '/mapa-do-site'
      preLoaderRoute: typeof MapaDoSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licitacoes': {
      id: '/licitacoes'
      path: '/licitacoes'
      fullPath: '/licitacoes'
      preLoaderRoute: typeof LicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leis': {
      id: '/leis'
      path: '/leis'
      fullPath: '/leis'
      preLoaderRoute: typeof LeisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional': {
      id: '/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof InstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/vereadores': {
      id: '/_authenticated/admin/vereadores'
      path: '/admin/vereadores'
      fullPath: '/admin/vereadores'
      preLoaderRoute: typeof AuthenticatedAdminVereadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/publicacoes': {
      id: '/_authenticated/admin/publicacoes'
      path: '/admin/publicacoes'
      fullPath: '/admin/publicacoes'
      preLoaderRoute: typeof AuthenticatedAdminPublicacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/projetos': {
      id: '/_authenticated/admin/projetos'
      path: '/admin/projetos'
      fullPath: '/admin/projetos'
      preLoaderRoute: typeof AuthenticatedAdminProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/paginas': {
      id: '/_authenticated/admin/paginas'
      path: '/admin/paginas'
      fullPath: '/admin/paginas'
      preLoaderRoute: typeof AuthenticatedAdminPaginasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/noticias': {
      id: '/_authenticated/admin/noticias'
      path: '/admin/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AuthenticatedAdminNoticiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/licitacoes': {
      id: '/_authenticated/admin/licitacoes'
      path: '/admin/licitacoes'
      fullPath: '/admin/licitacoes'
      preLoaderRoute: typeof AuthenticatedAdminLicitacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/leis': {
      id: '/_authenticated/admin/leis'
      path: '/admin/leis'
      fullPath: '/admin/leis'
      preLoaderRoute: typeof AuthenticatedAdminLeisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/documentos': {
      id: '/_authenticated/admin/documentos'
      path: '/admin/documentos'
      fullPath: '/admin/documentos'
      preLoaderRoute: typeof AuthenticatedAdminDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminDocumentosRoute: typeof AuthenticatedAdminDocumentosRoute
  AuthenticatedAdminLeisRoute: typeof AuthenticatedAdminLeisRoute
  AuthenticatedAdminLicitacoesRoute: typeof AuthenticatedAdminLicitacoesRoute
  AuthenticatedAdminNoticiasRoute: typeof AuthenticatedAdminNoticiasRoute
  AuthenticatedAdminPaginasRoute: typeof AuthenticatedAdminPaginasRoute
  AuthenticatedAdminProjetosRoute: typeof AuthenticatedAdminProjetosRoute
  AuthenticatedAdminPublicacoesRoute: typeof AuthenticatedAdminPublicacoesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVereadoresRoute: typeof AuthenticatedAdminVereadoresRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminDocumentosRoute: AuthenticatedAdminDocumentosRoute,
  AuthenticatedAdminLeisRoute: AuthenticatedAdminLeisRoute,
  AuthenticatedAdminLicitacoesRoute: AuthenticatedAdminLicitacoesRoute,
  AuthenticatedAdminNoticiasRoute: AuthenticatedAdminNoticiasRoute,
  AuthenticatedAdminPaginasRoute: AuthenticatedAdminPaginasRoute,
  AuthenticatedAdminProjetosRoute: AuthenticatedAdminProjetosRoute,
  AuthenticatedAdminPublicacoesRoute: AuthenticatedAdminPublicacoesRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminVereadoresRoute: AuthenticatedAdminVereadoresRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  InstitucionalRoute: InstitucionalRoute,
  LeisRoute: LeisRoute,
  LicitacoesRoute: LicitacoesRoute,
  MapaDoSiteRoute: MapaDoSiteRoute,
  OuvidoriaRoute: OuvidoriaRoute,
  ProjetosRoute: ProjetosRoute,
  PublicacoesRoute: PublicacoesRoute,
  SicRoute: SicRoute,
  TransparenciaRoute: TransparenciaRoute,
  VereadoresRoute: VereadoresRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
